# These environment variables must be set in CircleCI UI
#
# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
# DOCKER_USER    - login info for docker hub
# DOCKER_PASS

version: 2.1

workflows:
  version: 2
  pr-workflow:
    jobs:
      - task-to-run: &pr-filters
          filters:
            branches:
              ignore: main

  main-workflow:
    jobs:
      - task-to-run: &main-filters
          filters:
            branches:
              only: main
      - task-to-not-run:
          <<: *main-filters

jobs:
  task-to-run:
    docker:
      - image: ubuntu-2004:202101-01 # Ubuntu 20.04, Docker v20.10.2, Docker Compose v1.28.2
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - run: echo "this task runs"

  task-to-not-run:
    docker:
      - image: ubuntu-2004:202101-01 # Ubuntu 20.04, Docker v20.10.2, Docker Compose v1.28.2
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - run: echo "this task should bail out after this line, interrupting the workflow"
      - skip-if-do-not-deploy
      - run: echo "ERROR - this should never print"

commands:
  skip-if-do-not-deploy:
    steps:
      - run:
          name: Check if deployment is disallowed
          command: |
            if git log -1 "$CIRCLE_SHA1" | grep -q '\[do not deploy\]'; then
                echo "Skipping this step: deployment was disabled in the last commit."
                circleci-agent step halt
            fi
