# These environment variables must be set in CircleCI UI
#
# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
# DOCKER_USER    - login info for docker hub
# DOCKER_PASS

version: 2.1

workflows:
  version: 2
  pr-workflow:
    jobs:
      - task-to-run: &pr-filters
          filters:
            branches:
              ignore: main

  main-workflow:
    jobs:
      - task-to-run: &main-filters
          filters:
            branches:
              only: main
      - task-that-can-be-skipped:
          <<: *main-filters
      - unhold-to-deploy-to-prod: # <<< A job that will require manual approval in the CircleCI web application.
          <<: *main-filters
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
           - task-that-can-be-skipped
      # On approval of the `hold` job, any successive job that requires the `hold` job will run.
      # In this case, a user is manually triggering the deploy job.
      - deploy-to-prod:
          <<: *main-filters
          requires:
            - unhold-to-deploy-to-prod
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

jobs:
  publish:
    docker:
      - image: cimg/python:3.9.4
    steps:
      - checkout
      - when:
          condition:
            matches:
              pattern: "^v.*-pre.*$"
              value: << pipeline.git.tag >>
          steps:
            - run: echo "wOOT - Matched tag - Would push to 'pre'"
            - run: echo << pipeline.git.tag >>
      - when:
          condition:
            not:
              matches:
                pattern: "^v.*-pre.*$"
                value: << pipeline.git.tag >>
          steps:
            - run: echo "'pre' NOT MATCHED - Would push to release"
            - run: echo << pipeline.git.tag >>
  task-to-run:
    docker:
      - image: circleci/rust:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - run: echo "this task runs"

  task-that-can-be-skipped:
    docker:
      - image: circleci/rust:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run: echo "this task should bail out after this line, interrupting the workflow"
      - run: git log -1 "$CIRCLE_SHA1"
      - skip-if-do-not-deploy
      - run: echo "ERROR - this should never print"

  deploy-to-prod:
    docker:
      - image: circleci/rust:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - run: echo "this task runs"

commands:
  skip-if-do-not-deploy:
    steps:
      - run:
          name: Check if deployment is disallowed
          command: |
            if git log -1 "$CIRCLE_SHA1" | grep -q '\[do not deploy\]'; then
                echo "Skipping this step: deployment was disabled in the last commit."
                circleci-agent step halt
            fi
